/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiSearchRouteImport } from './routes/ai-search'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as PollRouteImport } from './routes/poll'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchRoute = AiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const PollRoute = PollRouteImport.update({
  id: '/poll',
  path: '/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants_/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-search': typeof AiSearchRoute
  '/deals': typeof DealsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/poll': typeof PollRoute
  '/restaurants': typeof RestaurantsRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-search': typeof AiSearchRoute
  '/deals': typeof DealsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/poll': typeof PollRoute
  '/restaurants': typeof RestaurantsRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-search': typeof AiSearchRoute
  '/deals': typeof DealsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/poll': typeof PollRoute
  '/restaurants': typeof RestaurantsRoute
  '/restaurants_/$id': typeof RestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-search'
    | '/deals'
    | '/join'
    | '/login'
    | '/map'
    | '/merchant'
    | '/poll'
    | '/restaurants'
    | '/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-search'
    | '/deals'
    | '/join'
    | '/login'
    | '/map'
    | '/merchant'
    | '/poll'
    | '/restaurants'
    | '/restaurants/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-search'
    | '/deals'
    | '/join'
    | '/login'
    | '/map'
    | '/merchant'
    | '/poll'
    | '/restaurants'
    | '/restaurants_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiSearchRoute: typeof AiSearchRoute
  DealsRoute: typeof DealsRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MerchantRoute: typeof MerchantRoute
  PollRoute: typeof PollRoute
  RestaurantsRoute: typeof RestaurantsRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search': {
      id: '/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll': {
      id: '/poll'
      path: '/poll'
      fullPath: '/poll'
      preLoaderRoute: typeof PollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants_/$id': {
      id: '/restaurants_/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiSearchRoute: AiSearchRoute,
  DealsRoute: DealsRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MerchantRoute: MerchantRoute,
  PollRoute: PollRoute,
  RestaurantsRoute: RestaurantsRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
